### ISSUE TITLE
Why does this command reset hard say permission denied?

### ISSUE THREAD

**Issue by not1951aw** [ufocomp/apostol-ocpp#13]
{
  "error": {
    "code": 400,
    "message": "InternalError: (13: Permission denied)"
  }
}

**Comment by ufocomp** [comment]
Hello! Because the application is running as a user with insufficient permissions to execute this command. The `reset hard` command restarts the operating system.

Change the settings in the /etc/cs/cs.conf file

```
## OCPP Service config file

[main]
user=root
group=root

```
Instead of root, you can specify any user who has permission to restart the operating system.

P.S.
This user must also have write access to the `/etc/cs/cp/*` folder. In this case, the error occurs for this reason.
